spring.application.name=TouristManagementApi

server.servlet.context-path=/TouristMangament

spring.datasource.url=jdbc:mysql://localhost:3306/student_info
spring.datasource.username=root
spring.datasource.password=Yash@2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update